### ISSUE TITLE
More APIs support (IMDB and TMDb)

### ISSUE THREAD

**Issue by victorgveloso** [BeeeQueue/arm-server#270]
I really appreciate your work with arm-server and Yuna. One thing would be awesome to have included here is support for other non-anime exclusive content APIs (like IMDB, TVDB and TMDb). Their catalogs have all animes that I know and it'd allow arm-server to be an awesome middleware for integration between those platforms!

- [ ] IMDB's id
- [ ] TMDb's id

[TMDb's API has an endpoint](https://developers.themoviedb.org/3/getting-started/external-ids) useful for other APIs integration. I really recommend using it (It's currently free and unlimited)

**Comment by BeeeQueue** [comment]
Currently this service is just a REST API for getting data from [`anime-offline-database`](https://github.com/manami-project/anime-offline-database/). This feature would increase the scope to an ID mapper as well, which I've been thinking about doing.

e.g. checking any suspicious, lonely `anidb` entries for if they have a mapping some other way.

Then we could at the same time try to check for IMDB and TMDb entries as well.
