### ISSUE TITLE
Any valid POST request returns a "400" validation error

### ISSUE THREAD

**Issue by VeikkoLehmuskorpi** [BeeeQueue/arm-server#324]
Any valid POST request to `https://relations.yuna.moe/api/ids` returns an error with status code 400 and a validation error message. 

For example, trying to fetch the relations for the [Berserk](https://anilist.co/anime/33/Berserk/) anime
```
curl -XPOST -H "Content-Type: application/json" -d "{ \"anilist\": 33 }" "https://relations.yuna.moe/api/ids"
```

returns `{"code":400,"error":"Bad Request","validation":"\"value\" does not match any of the allowed types"}` instead of a list of IDs.

I've tried doing the requests with code, Postman, curl and cannot see any mistakes in my requests. Fetching the relations for the same anime via query parameters works but then you're limited to fetching just one anime at a time.

**Comment by BeeeQueue** [comment]
Seems like the validation schema doesn't allow a single object as query, for now you can work around this by just surrounding the query in an array `[{ ... }]`

**Comment by BeeeQueue** [comment]
Fixed
