### ISSUE TITLE
Zenarmor Malware/Virus includes host

### ISSUE THREAD

**Issue by lenisko** [beeequeue/arm-server#839]
Just leaving a note that `Zenarmor :: Malware/Virus` list matches a hostname `arm.haglund.dev`
Reported it for removal through form, but I'm not sure if it's enough.

Cheers!

**Comment by beeequeue** [comment]
Never heard of them, can't be a very good service if it makes mistakes like marking my `haglund.dev` domain as malware.

Can reopen if this somehow is a problem for enough people
